# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='notes',
        ),
        migrations.AddField(
            model_name='notes',
            name='reply',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='blog.Reply'),
        ),
    ]
