# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-21 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20161221_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatcontent',
            old_name='uer',
            new_name='user',
        ),
    ]
