# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20161221_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatcontent',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
