# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_user_portrait'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='static/portrait/'),
        ),
    ]
