# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-05 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170205_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='blog.User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='portrait',
            field=models.ImageField(blank=True, upload_to='portrait/'),
        ),
    ]
